#Application Configuration
server:
  port: 8082

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:

  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://localhost/clientes?allowPublicKeyRetrieval=true&serverTimezone=America/Bogota&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    #platform: mysql
    username: root
    password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
